# Datset not on the HF Hub

## Loading a local dataset

In [ ]:
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz

--2026-07-14 07:31:57--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz [following]
--2026-07-14 07:31:57--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7725286 (7.4M) [application/octet-stream]
Saving to: ‘SQuAD_it-train.json.gz’

SQuAD_it-train.json 100%[===================>]   7.37M  --.-KB/s    in 0.09s

2026-07-14 07:31:58 (79.9 MB/s) - ‘SQuAD_it-train.json.gz’ saved [7725286/7725286]

--2026-07-14 07:31:58--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz [following]
--2026-07-14 07:31:58--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1051245 (1.0M) [application/octet-stream]
Saving to: ‘SQuAD_it-test.json.gz’

SQuAD_it-test.json. 100%[===================>]   1.00M  --.-KB/s    in 0.05s

2026-07-14 07:31:58 (20.1 MB/s) - ‘SQuAD_it-test.json.gz’ saved [1051245/1051245]

In [ ]:
!gzip -dkv SQuAD_it-*.json.gz

SQuAD_it-test.json.gz:	 87.5% -- created SQuAD_it-test.json
SQuAD_it-train.json.gz:	 82.3% -- created SQuAD_it-train.json

To load a JSON file with the load_dataset() function, we just need to know if we’re dealing with ordinary JSON (similar to a nested dictionary) or JSON Lines (line-separated JSON).

This dataset uses the nested format, with all the text stored in a `data` field. This means we can load the dataset by specifying the `field` argument as follows:

In [ ]:
from datasets import load_dataset

squad_it_dataset = load_dataset("json", data_files="SQuAD_it-train.json", field="data")

Generating train split: 0 examples [00:00, ? examples/s]

By default loading the local dataset creates a `DatasetDict` object with a `train` split

In [ ]:
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
})

In [ ]:
squad_it_dataset["train"][0]

{'title': 'Terremoto del Sichuan del 2008',
 'paragraphs': [{'context': "Il terremoto del Sichuan del 2008 o il terremoto del Gran Sichuan, misurato a 8.0 Ms e 7.9 Mw, e si è verificato alle 02:28:01 PM China Standard Time all' epicentro (06:28:01 UTC) il 12 maggio nella provincia del Sichuan, ha ucciso 69.197 persone e lasciato 18.222 dispersi.",
   'qas': [{'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56cdca7862d2951400fa6826',
     'question': 'In quale anno si è verificato il terremoto nel Sichuan?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56cdca7862d2951400fa6828',
     'question': 'Quante persone sono state uccise come risultato?'},
    {'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56d4f9902ccc5a1400d833c0',
     'question': 'Quale anno ha avuto luogo il terremoto del Sichuan?'},
    {'answers': [{'answer_start': 78, 'text': '8.0 Ms e 7.9 Mw'}],
     'id': '56d4f9902ccc5a1400d833c1',
     'question': 'Che cosa ha fatto la misura di sisma?'},
    {'answers': [{'answer_start': 183, 'text': '12 maggio'}],
     'id': '56d4f9902ccc5a1400d833c2',
     'question': 'Che giorno si è verificato il terremoto?'},
    {'answers': [{'answer_start': 118,
       'text': '02:28:01 PM China Standard Time'}],
     'id': '56d4f9902ccc5a1400d833c3',
     'question': 'Che ora del giorno è accaduto il terremoto?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56d4f9902ccc5a1400d833c4',
     'question': 'Quante persone sono morte?'}]},
  {'context': 'E\' noto anche come terremoto di Wenchuan (Cinese:????; pinyin: Wènchu? n dà dìzhèn; letteralmente:"Grande terremoto di Wenchuan"), dopo l\' ubicazione dell\' epicentro del terremoto, Wenchuan County, Sichuan. L\' epicentro era di 80 chilometri (50 miglia) ad ovest nord-ovest di Chengdu, capoluogo di provincia, con una profondità focale di 19 km (12 miglia). Il terremoto ha colpito anche i paesi vicini e lontani da Pechino e Shanghai-1.500 km (930 mi) e 1.700 km (1.060 mi) di distanza, dove gli edifici adibiti a uffici hanno oscillato con il tremore. Forti scosse di assestamento, un po\' superiori alla magnitudo 6, hanno continuato a colpire l\' area anche mesi dopo il sisma principale, causando nuove vittime e danni.',
   'qas': [{'answers': [{'answer_start': 415, 'text': 'Pechino e Shanghai'}],
     'id': '56cdcb2c62d2951400fa6830',
     'question': 'Quali città lontane in altri paesi potrebbero sentire il terremoto?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56cdcb2c62d2951400fa6833',
     'question': 'Qual è stata la profondità focale del terremoto?'},
    {'answers': [{'answer_start': 659, 'text': 'mesi dopo'}],
     'id': '56cdcb2c62d2951400fa6834',
     'question': 'Quanto tempo dopo il terremoto si sono sentite le scosse di assestamento?'},
    {'answers': [{'answer_start': 181, 'text': 'Wenchuan County, Sichuan'}],
     'id': '56d4fb6f2ccc5a1400d833d5',
     'question': "Dov' era l' epicentro del terremoto?"},
    {'answers': [{'answer_start': 227, 'text': '80 chilometri'}],
     'id': '56d4fb6f2ccc5a1400d833d6',
     'question': 'Quanto lontano era da Chengdu?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56d4fb6f2ccc5a1400d833d7',
     'question': 'Qual era la profondità focale del sisma?'}]},
  {'context': "I dati ufficiali (al 21 luglio 2008 ore 12:00 CST) hanno dichiarato che 69.197 sono stati confermati morti, di cui 68.636 nella provincia del Sichuan e 374.176 feriti, di cui 18.222 scomparsi. Il terremoto ha lasciato circa 4,8 milioni di senzatetto, anche se il numero potrebbe raggiungere gli 11 milioni. Circa 15 milioni di persone vivevano nell' area colpita. E' stato il terremoto più mortale per colpire la Cina dopo il terremoto di Tangshan 1976, che ha ucciso almeno 240.000 persone, e il più forte del paese dal terremoto di Chayu 1950, che ha registrato a 8,5 sulla scala di magnitudo Richter. E' il 21° terremoto più morto di tutti i tempi. Il 6 novembre 2008, il governo centrale ha annunciato che avrebbe speso 1 trilione di RMB (circa 146,5 miliardi di dollari USA) nei prossimi tre anni per ricostruire le aree devastate dal terremoto, come parte del programma cinese di stimolo economico.",
   'qas': [{'answers': [{'answer_start': 72, 'text': '69.197'}],
     'id': '56cdcbb762d2951400fa683a',
     'question': 'Quante persone sono state confermate morte?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56cdcbb762d2951400fa683b',
     'question': 'Quanti morti sono stati confermati solo nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56cdcbb762d2951400fa683c',
     'question': 'Quante persone sono rimaste senza tetto a causa del terremoto?'},
    {'answers': [{'answer_start': 313, 'text': '15 milioni'}],
     'id': '56cdcbb762d2951400fa683d',
     'question': 'Quante persone hanno vissuto nella zona colpita?'},
    {'answers': [{'answer_start': 724, 'text': '1 trilione di RMB'}],
     'id': '56cdcbb762d2951400fa683e',
     'question': 'Quanto denaro è stato destinato alla ricostruzione di aree devastate?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56d4fca52ccc5a1400d833de',
     'question': 'Quante persone sono morte nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 152, 'text': '374.176'}],
     'id': '56d4fca52ccc5a1400d833df',
     'question': 'Quanti sono stati feriti nel Sichuan?'},
    {'answers': [{'answer_start': 175, 'text': '18.222'}],
     'id': '56d4fca52ccc5a1400d833e0',
     'question': 'Quante persone sono elencate come scomparse?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56d4fca52ccc5a1400d833e1',
     'question': 'Quante persone sono senzatetto a causa del terremoto?'},
    {'answers': [{'answer_start': 295, 'text': '11 milioni'}],
     'id': '56d4fca52ccc5a1400d833e2',
     'question': 'Quanto potrebbe arrivare il numero dei senzatetto?'}]},
  {'context': "Il terremoto ha avuto una magnitudine di 8,0 Ms e 7,9 Mw. L' epicentro è stato in Wenchuan County, Ngawa Tibetano e Prefettura Autonoma di Qiang, 80 km ad ovest / nord-ovest del capoluogo di provincia di Chengdu, con il suo tremore principale che si verifica alle 14:28:01.42 China Standard Time (06:28:01.42 UTC), il 12 maggio 2008 della durata di circa 2 minuti, nel terremoto quasi l' 80% degli edifici sono stati distrutti.",
   'qas': [{'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56cdcc5562d2951400fa6847',
     'question': 'Quanto tempo è durato il terremoto?'},
    {'answers': [{'answer_start': 388, 'text': '80%'}],
     'id': '56cdcc5562d2951400fa6848',
     'question': 'Quale percentuale di edifici è stata distrutta?'},
    {'answers': [{'answer_start': 41, 'text': '8,0 Ms e 7,9 Mw'}],
     'id': '56d4fe332ccc5a1400d833e8',
     'question': 'Qual era la magnitudo del terremoto?'},
    {'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56d4fe332ccc5a1400d833eb',
     'question': 'Quanto tempo è durato il tremore principale?'},
    {'answers': [{'answer_start': 379, 'text': "quasi l' 80%"}],
     'id': '56d4fe332ccc5a1400d833ec',
     'question': 'Quale percentuale di edifici è stata distrutta durante il sisma?'}]},
  {'context': "Secondo uno studio della China Earthquake Administration (CEA), il terremoto si è verificato lungo la faglia Longmenshan, una struttura di spinta lungo il confine della piastra Indo-Australiana e placca eurasiatica. Le attività sismiche si sono concentrate sulla sua frattura media (nota come frattura Yingxiu-Beichuan). La rottura è durata quasi 120 sec, con la maggior parte dell' energia rilasciata nei primi 80 sec. Partendo da Wenchuan, la rottura si propagò ad una velocità media di 3,1 chilometri al secondo 49° verso nord-est, rompendosi per un totale di circa 300 km. Lo spostamento massimo ammontava a 9 metri. Il fuoco era più profondo di 10 km.",
   'qas': [{'answers': [{'answer_start': 347, 'text': '120 sec'}],
     'id': '56cdccd962d2951400fa6850',
     'question': 'Quanto tempo ha durato la rottura?'},
    {'answers': [{'answer_start': 650, 'text': '10 km'}],
     'id': '56cdccd962d2951400fa6852',
     'question': 'Quanto è stato profondo il centro del terremoto?'},
    {'answers': [{'answer_start': 293, 'text': 'frattura Yingxiu-Beichuan'}],
     'id': '56d5005d2ccc5a1400d833f4',
     'question': 'Su quale frattura ha messo a fuoco il terremoto?'},
    {'answers': [{'answer_start': 612, 'text': '9 metri'}],
     'id': '56d5005d2ccc5a1400d833f6',
     'question': 'Qual è stato lo sfollamento più causato dal terremoto?'}]},
  {'context': 'Yazhou Zhoukan, con sede in Malesia, ha condotto un\' intervista con l\' ex ricercatore presso il China Seismological Bureau Geng Qingguo (??), in cui Geng ha sostenuto che un rapporto scritto riservato è stato inviato all\' Ufficio sismologico di Stato il 30 aprile 2008, avvertendo circa il possibile verificarsi di un terremoto significativo nella regione della prefettura di Ngawa del Sichuan intorno all\' 8 maggio, con una gamma di 10 giorni prima o dopo il terremoto. Il Geng, pur riconoscendo che la predizione del terremoto era ampiamente considerata problematica dalla comunità scientifica, credeva che "più grande è il terremoto, più facile è prevedere". Geng aveva a lungo tentato di stabilire una correlazione tra il verificarsi di siccità e terremoti; Premier Zhou Enlai ha riferito che ha preso interesse nel lavoro di Geng. La teoria di correlazione siccità-terra terremoto di Geng è stata pubblicata per la prima volta nel 1972, e ha detto di aver pronosticato con successo i terremoti di Haicheng 1975 e 1976 Tangshan. Lo stesso articolo di Yazhou Zhoukan ha sottolineato le difficoltà intrinseche associate alla previsione dei terremoti.',
   'qas': [{'answers': [{'answer_start': 936, 'text': '1972'}],
     'id': '56cdce0b62d2951400fa685b',
     'question': 'Quando è stata rilasciata la teoria di correlazione siccità-terra terremoto di Geng?'},
    {'answers': [{'answer_start': 394, 'text': "intorno all' 8 maggio"}],
     'id': '56d67a8d1c8504140094714f',
     'question': 'Qual era il tempo previsto per il terremoto?'},
    {'answers': [{'answer_start': 741, 'text': 'siccità'}],
     'id': '56d67a8d1c85041400947150',
     'question': 'Che cosa ha cercato Geng a lungo di stabilire come rapporto con i terremoti?'}]},
  {'context': 'In uno studio dell\' USGS (United States Geological Survey) i modelli preliminari di rottura del terremoto hanno indicato uno spostamento fino a 9 metri lungo un guasto lungo circa 240 km di lunghezza e 20 km di profondità. Il terremoto ha generato deformazioni della superficie superiori a 3 metri e ha aumentato lo stress (e la probabilità che si verifichino eventi futuri) alle estremità nord-orientale e sud-occidentale del guasto. Il 20 maggio, il sismologo dell\' USGS Tom Parsons ha avvertito che c\' è "alto rischio" di una grave scossa di assestamento M>7 nelle prossime settimane o mesi.',
   'qas': [{'answers': [{'answer_start': 137, 'text': 'fino a 9 metri'}],
     'id': '56cdcebe62d2951400fa6862',
     'question': 'Quanto è stato grande lo spostamento?'},
    {'answers': [{'answer_start': 473, 'text': 'Tom Parsons'}],
     'id': '56cdcebe62d2951400fa6866',
     'question': "Chi ha prima messo in guardia da possibili attività sismiche nell' area?"},
    {'answers': [{'answer_start': 144, 'text': '9 metri'}],
     'id': '56d5027a9d1b871400ae05e1',
     'question': "Che cosa ha mostrato il Geological Survey degli Stati Uniti come l' entità dello spostamento?"},
    {'answers': [{'answer_start': 202, 'text': '20 km di profondità'}],
     'id': '56d5027a9d1b871400ae05e3',
     'question': 'Quanto è profondo il guasto?'},
    {'answers': [{'answer_start': 508, 'text': 'alto rischio'}],
     'id': '56d5027a9d1b871400ae05e5',
     'question': 'Che cosa ha considerato Tom Parsons come il fattore di rischio per forti terremoti futuri?'}]},
  {'context': 'Sismologo giapponese Yuji Yagi Yuji Yagi presso l\' Università di Tsukuba ha detto che il terremoto si è verificato in due fasi:"Il 155 miglia Longmenshan Fault tore in due sezioni, il primo uno strappo di circa sette metri, seguita da un secondo che ha tosato quattro metri". I suoi dati hanno anche mostrato che il terremoto è durato circa due minuti e ha rilasciato 30 volte l\' energia del grande terremoto di Hanshin del 1995 in Giappone, che ha ucciso oltre 6.000 persone. Egli ha sottolineato che la scarsità dell\' epicentro e la densità di popolazione hanno notevolmente aumentato la gravità del terremoto. Teruyuki Kato, un sismologo dell\' Università di Tokyo, ha detto che le onde sismiche del terremoto hanno percorso una lunga distanza senza perdere il loro potere a causa della fermezza del terreno nella Cina centrale.',
   'qas': [{'answers': [{'answer_start': 115, 'text': 'in due fasi'}],
     'id': '56d504539d1b871400ae05eb',
     'question': 'Come ha fatto Yuji Yagi a dire che il terremoto è successo?'},
    {'answers': [{'answer_start': 142, 'text': 'Longmenshan Fault'}],
     'id': '56d504539d1b871400ae05ec',
     'question': 'Che errore si è verificato in due luoghi?'},
    {'answers': [{'answer_start': 368, 'text': '30 volte'}],
     'id': '56d504539d1b871400ae05ee',
     'question': 'Quanta più energia di quella prodotta dal terremoto del 1995 in Giappone?'},
    {'answers': [{'answer_start': 789, 'text': 'fermezza del terreno'}],
     'id': '56d504539d1b871400ae05ef',
     'question': 'Perché le onde sismiche hanno viaggiato finora?'}]},
  {'context': 'Tra 64 e 104 scosse di assestamento importanti, di magnitudo compresa tra 4,0 e 6,1, sono state registrate entro 72 ore dal sisma principale. Secondo i conteggi ufficiali cinesi,"alle ore 12:00 CST, 6 novembre 2008 c\' erano state 42.719 scariche post-shock totali, di cui 246 variavano da 4,0 SM a 4,9 SM, 34 da 5,0 MS a 5,9 MS, e 8 da 6,0 Ms a 6,4 MS; l\' urto post-shock più forte misurato 6,4 MS." L\' ultima scossa post-shock superiore a M6 si è verificato il 5 agosto.',
   'qas': [{'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56cdd08862d2951400fa6894',
     'question': 'Quante sono state le scosse di assestamento?'},
    {'answers': [{'answer_start': 107,
       'text': 'entro 72 ore dal sisma principale'}],
     'id': '56cdd08862d2951400fa6896',
     'question': 'Quando sono state registrate le scosse di assestamento?'},
    {'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56d505f99d1b871400ae05f5',
     'question': 'Quante sono state le scosse di assestamento entro 72 ore?'},
    {'answers': [{'answer_start': 230, 'text': '42.719'}],
     'id': '56d505f99d1b871400ae05f6',
     'question': 'Che cosa dicono i cinesi è il numero totale di shock dopo il terremoto?'},
    {'answers': [{'answer_start': 272, 'text': '246'}],
     'id': '56d505f99d1b871400ae05f8',
     'question': 'In quale data si sono verificate le scosse di assestamento più recenti superiori a 6 SM?'}]},
  {'context': '(Il terremoto della sig. ra 6.1 del 30 agosto 2008 nel Sichuan meridionale non faceva parte di questa serie perché è stato causato da una diversa colpa.',
   'qas': [{'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a0',
     'question': 'Dove si è verificato il terremoto?'},
    {'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a2',
     'question': "Dov' era il terremoto del 30 agosto 2008?"},
    {'answers': [{'answer_start': 20, 'text': 'sig'}],
     'id': '56d507269d1b871400ae05ff',
     'question': 'Qual era la grandezza del terremoto del Sichuan meridionale?'}]},
  {'context': 'La mappa dell\' intensità sismica pubblicata dal CEA dopo aver rilevato 500.000 km2 dell\' area colpita mostra una liedu massima di XI sulla scala di intensità sismica cinese (CSIS), descritta come "molto distruttiva" sulla scala macrosismica europea (EMS) da cui il CSIS ha tratto riferimento. (USGS, utilizzando la scala di intensità Mercalli modificata (CC), collocava anche l\' intensità massima a XI,"molto disastrosa". Due strisce sud-ovest-nord-est di liedu XI sono centrate intorno a Yingxiu, Wenchuan (la città più vicina all\' epicentro del terremoto principale) e Beichuan (la città ripetutamente colpita da forti scosse di assestamento tra cui una che registra MS 6.1 il 1 agosto 2008), entrambe nella provincia del Sichuan, occupando un totale di 2.419 km2. La zona Yingxiu liedu-XI è lunga circa 66 km e larga 20 km lungo Wenchuan-Dujiangyan-Pengzhou; la zona Beichuan liedu-XI è lunga circa 82 km e larga 15 km lungo An County-Beichuan-Pingwu. L\' area con liedu X (comparabile a X su EMS,"distruttivo" e X su MM,"disastroso") ha una superficie di 3.144 km2.',
   'qas': [{'answers': [{'answer_start': 48, 'text': 'CEA'}],
     'id': '56cdd21562d2951400fa68b0',
     'question': "Chi ha pubblicato la mappa dell' intensità dei terremoti?"},
    {'answers': [{'answer_start': 130, 'text': 'XI'}],
     'id': '56cdd21562d2951400fa68b2',
     'question': 'A quale intensità è stata scalata?'},
    {'answers': [{'answer_start': 489, 'text': 'Yingxiu, Wenchuan'}],
     'id': '56d5098a9d1b871400ae0609',
     'question': "Quale città era più vicina all' epicentro principale?"}]},
  {'context': "Il sistema Longmen Shan Fault System si trova al confine orientale dell' altopiano tibetano e contiene diversi difetti. Questo terremoto ha rotto almeno due strutture imbricate in Longmen Shan Fault System, vale a dire il Fault Beichuan e il Guanxian-Anxian Fault. Nell' area epicentrale, lo slittamento medio in Fault Beichuan era di circa 3,5 metri (11 ft) verticale, di 3,5 metri (11 ft) orizzontale parallelo al guasto, e di 4,8 metri (16 ft) orizzontale-pendicolare al guasto. Nell' area di circa 30 chilometri (19 miglia) a nord-est dell' epicentro, lo scivolamento superficiale su Beichuan Fault è stato quasi esclusivamente dextral strike-slip fino a circa 3 metri, mentre lo scivolamento medio in Guanxian-Anxian Fault è stato di circa 2 metri verticali (6 ft 7 in) e 2,3 metri (7 ft 7 in) orizzontali. il confine orientale dell' altopiano tibetano.",
   'qas': [{'answers': [{'answer_start': 665, 'text': '3 metri'}],
     'id': '56cdd4d762d2951400fa68cd',
     'question': 'Quanto è stato grande lo slip 30 km a nord-est del guasto?'},
    {'answers': [{'answer_start': 745, 'text': '2 metri'}],
     'id': '56cdd4d762d2951400fa68ce',
     'question': 'Qual è stato lo slittamento verticale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 777, 'text': '2,3 metri'}],
     'id': '56cdd4d762d2951400fa68cf',
     'question': 'Che cosa è stato lo slittamento orizzontale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 73, 'text': 'altopiano tibetano'}],
     'id': '56cdd4d762d2951400fa68d0',
     'question': 'Dove si trova il guasto dello shan Longmen?'},
    {'answers': [{'answer_start': 3,
       'text': 'sistema Longmen Shan Fault System'}],
     'id': '56d516439d1b871400ae0611',
     'question': 'Dove sono i guasti Beichuan e Guanxian-Ansia?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0612',
     'question': 'Qual è stato lo slittamento verticale medio nel difetto di Beichaun?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0613',
     'question': "Qual è stato lo slittamento orizzontale nel Fault Beichuan all' epicentro?"},
    {'answers': [{'answer_start': 429, 'text': '4,8 metri'}],
     'id': '56d516439d1b871400ae0614',
     'question': 'Qual è stato lo slittamento orizzontale perpendicolare al guasto?'}]},

We want both the `train` and `test` split in a single `DatasetDict` object so that we can apply the `Dataset.map()` function across both the splits at once

In [ ]:
data_files = {"train": "SQuAD_it-train.json", "test": "SQuAD_it-test.json"}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")
squad_it_dataset

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

## Loading a remote dataset

In [ ]:
url = "https://github.com/crux82/squad-it/raw/master/"
data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz",
}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")

Downloading data:   0%|          | 0.00/7.73M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/1.05M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [ ]:
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

# Slicing and dicing our dataset

## Slice and dice

In [1]:
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"
!unzip drugsCom_raw.zip

--2026-07-16 14:36:13--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip’

drugsCom_raw.zip        [     <=>            ]  41.00M  39.7MB/s    in 1.0s

2026-07-16 14:36:15 (39.7 MB/s) - ‘drugsCom_raw.zip’ saved [42989872]

Archive:  drugsCom_raw.zip
  inflating: drugsComTest_raw.tsv
  inflating: drugsComTrain_raw.tsv

In [2]:
from datasets import load_dataset

data_files = {"train": "drugsComTrain_raw.tsv", "test": "drugsComTest_raw.tsv"}
# \t is the tab character in Python
# Using the delimiter argument because it is a tsv file which is a tab seperated file
drug_dataset = load_dataset("csv", data_files=data_files, delimiter="\t")

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

A good practise of doing data anaysis is grabing a small amount of random data to get a quick feel of the data.

We can create a random sample of data by chaining the `Dataset.shuffle()` and `Dataset.select()` function

In [3]:
drug_sample = drug_dataset["train"].shuffle(seed=42).select(range(1000))
# Peek at the first few examples
drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

Here, to test if the `Unnamed: 0` column belong to the patients id, we can use the `Dataset.unique()` function to verify the number of IDs match the number of rows in each split

In [4]:
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

In [5]:
len(drug_dataset['train'])

161297

In [6]:
len(drug_dataset['train'].unique('Unnamed: 0'))

161297

Renaming the `Unnamed: 0` column to something interpretable using the `DatasetDict.rename_column()` function to rename the column across both splits.

In [7]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0", new_column_name="patient_id"
)
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

Normalize the condition column to have only the lowercase letters

We see that some of the entries in the condition columns are None, so we will drop them using the `Dataset.filter()` function

In [8]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

Filter:   0%|          | 0/161297 [00:00<?, ? examples/s]

Filter:   0%|          | 0/53766 [00:00<?, ? examples/s]

In [9]:
def change_to_lowercase(example):
  return {"condition": example["condition"].lower()}

drug_dataset = drug_dataset.map(change_to_lowercase)

Map:   0%|          | 0/160398 [00:00<?, ? examples/s]

Map:   0%|          | 0/53471 [00:00<?, ? examples/s]

In [10]:
# Check that lowercasing worked
drug_dataset["train"]["condition"]

Column(['left ventricular dysfunction', 'adhd', 'birth control', 'birth control', 'opiate dependence'])

## Creating new columns

Count the number of words in each review

In [11]:
def compute_review_length(example):
  return {"review_length": len(example['review'].split())}

The `compute_review_length` function returns a dictionary whose keys doesn't correspond to one of the column names in the dataset. In this case, when `compute_review_length()` is passed to `Dataset.map()`, it will be applied to all the rows in the dataset to create a new review_length column

In [12]:
drug_dataset = drug_dataset.map(compute_review_length)
# Inspect the first training example
drug_dataset["train"][0]

Map:   0%|          | 0/160398 [00:00<?, ? examples/s]

Map:   0%|          | 0/53471 [00:00<?, ? examples/s]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

We can now sort the dataset according to the `review_length` column using the `Dataset.sort()` function

In [13]:
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [111469, 13653, 53602],
 'drugName': ['Ledipasvir / sofosbuvir',
  'Amphetamine / dextroamphetamine',
  'Alesse'],
 'condition': ['hepatitis c', 'adhd', 'birth control'],
 'review': ['"Headache"', '"Great"', '"Awesome"'],
 'rating': [10.0, 10.0, 10.0],
 'date': ['February 3, 2015', 'October 20, 2009', 'November 23, 2015'],
 'usefulCount': [41, 3, 0],
 'review_length': [1, 1, 1]}

Now, we'll remove all the rows whose `review_length` is less than 30

In [14]:
drug_dataset = drug_dataset.filter(lambda x: x['review_length'] > 30)
drug_dataset

Filter:   0%|          | 0/160398 [00:00<?, ? examples/s]

Filter:   0%|          | 0/53471 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

## Dataset to Dataframe and vice versa

The `Dataset.set_format()` function changes the output format of the dataset without affecting the underlying data format. This happens in place

In [15]:
drug_dataset.set_format("pandas")

In [19]:
drug_dataset['train'][:3]

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89

Let's create a `pandas.DataFrame` for the whole training set

In [20]:
train_df = drug_dataset["train"][:]

In [21]:
frequencies = (
    train_df["condition"]
    .value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "count": "frequency"})
)
frequencies.head()

       condition  frequency
0  birth control      27655
1     depression       8023
2           acne       5209
3        anxiety       4991
4           pain       4744

Once we are done with out pandas analysis, we can always create a new `Dataset` object by using the `Dataset.from_pandas()` function

In [22]:
from datasets import Dataset

freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['condition', 'frequency'],
    num_rows: 819
})

## Creating a Validation set

In [26]:
drug_dataset_clean = drug_dataset["train"].train_test_split(train_size=0.8, seed=42)
# Rename the default "test" split to "validation"
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")
# Add the "test" set to our `DatasetDict`
drug_dataset_clean["test"] = drug_dataset["test"]
drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

## Saving a dataset

`Datasets` provides 3 main function:

- `Dataset.save_to_disk()` -> Arrow dataformat
- `Dataset.to_csv()` -> CSV
- `Dataset.to_json()` -> JSON

In [27]:
drug_dataset_clean.save_to_disk("drug_reviews")

Saving the dataset (0/1 shards):   0%|          | 0/110811 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/27703 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/46108 [00:00<?, ? examples/s]

We can load the dataset

In [30]:
from datasets import load_from_disk

drug_dataset_reloaded = load_from_disk("/content/drug_reviews")
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

For the CSV and JSON formats, we have to store each split as a separate file. One way to do this is by iterating over the keys and values in the `DatasetDict` object

In [31]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format:   0%|          | 0/111 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/28 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/47 [00:00<?, ?ba/s]